Traceback (most recent call last):
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\jupyter_ai\chat_handlers\base.py", line 125, in on_message
    await self.process_message(message)
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\jupyter_ai\chat_handlers\generate.py", line 276, in process_message
    final_path = await self._generate_notebook(prompt=message.body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\jupyter_ai\chat_handlers\generate.py", line 252, in _generate_notebook
    outline = await generate_outline(prompt, llm=self.llm, verbose=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\jupyter_ai\chat_handlers\generate.py", line 55, in generate_outline
    outline = await chain.apredict(description=description)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain\chains\llm.py", line 310, in apredict
    return (await self.acall(kwargs, callbacks=callbacks))[self.output_key]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_core\_api\deprecation.py", line 157, in awarning_emitting_wrapper
    return await wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain\chains\base.py", line 428, in acall
    return await self.ainvoke(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain\chains\base.py", line 212, in ainvoke
    raise e
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain\chains\base.py", line 203, in ainvoke
    await self._acall(inputs, run_manager=run_manager)
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_core\language_models\llms.py", line 643, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_core\language_models\llms.py", line 1018, in agenerate
    output = await self._agenerate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_core\language_models\llms.py", line 882, in _agenerate_helper
    raise e
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_core\language_models\llms.py", line 866, in _agenerate_helper
    await self._agenerate(
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_core\language_models\llms.py", line 1336, in _agenerate
    await self._acall(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\langchain_community\llms\together.py", line 188, in _acall
    async with session.post(
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\aiohttp\client.py", line 608, in _request
    await resp.start(conn)
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\aiohttp\client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\relat\anaconda3\envs\jupyter-ai\Lib\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
